#!/bin/bash

export REVISION=$(git rev-parse HEAD)

echo "Setup k8s template"
# Pull sensetive data from ENV
envsubst < deploy/secrets/application-secrets.yaml.tmpl > deploy/secrets/application-secrets.yaml
kubectl apply -f deploy/secrets/application-secrets.yaml
rm deploy/secrets/application-secrets.yaml

echo "Run deploy"
envsubst < deploy/deployments/juniorjobs.yaml.tmpl > deploy/deployments/juniorjobs.yaml
kubectl apply -R -f deploy/
rm deploy/deployments/juniorjobs.yaml
