#!/bin/sh
 
# Install kubernetes and set config
curl -LO https://storage.googleapis.com/kubernetes-release/release/1.8.7/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
 
mkdir ${HOME}/.kube
cp deploy/standalone/kubeconfig.template ${HOME}/.kube/config
 
# Fill out missing params in kubectl config file
kubectl config set clusters.kubernetes.certificate-authority-data "$KUBE_CLUSTER_CERTIFICATE"
kubectl config set clusters.kubernetes.server "$KUBE_CLUSTER_SERVER"
kubectl config set users.kubernetes-admin.client-certificate-data "$KUBE_CLIENT_CERTIFICATE"
kubectl config set users.kubernetes-admin.client-key-data "$KUBE_CLIENT_KEY"
