#!/bin/bash
 
# Install kubernetes and set config
echo "Install Kubectl"
#curl -LO https://storage.googleapis.com/kubernetes-release/release/1.8.7/bin/linux/amd64/kubectl
#chmod +x ./kubectl

sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF > kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF

sudo mv kubernetes.list /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl=1.8.7-00

mkdir ${HOME}/.kube
cp deploy/standalone/kubeconfig.template ${HOME}/.kube/config
 
echo "Setup kubectl access"
# Fill out missing params in kubectl config file
kubectl config set clusters.kubernetes.certificate-authority-data "$KUBE_CLUSTER_CERTIFICATE"
kubectl config set clusters.kubernetes.server "$KUBE_CLUSTER_SERVER"
kubectl config set users.kubernetes-admin.client-certificate-data "$KUBE_CLIENT_CERTIFICATE"
kubectl config set users.kubernetes-admin.client-key-data "$KUBE_CLIENT_KEY"
